version: 2.0.{build}
skip_tags: true
image: Visual Studio 2017
build_script:
  - ps: (Get-Content XmlSchemaClassGenerator\XmlSchemaClassGenerator.csproj).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content XmlSchemaClassGenerator\XmlSchemaClassGenerator.csproj
  - ps: (Get-Content XmlSchemaClassGenerator.Console\XmlSchemaClassGenerator.Console.csproj).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content XmlSchemaClassGenerator.Console\XmlSchemaClassGenerator.Console.csproj
  - dotnet restore
  - dotnet build -c Release
  - dotnet publish XmlSchemaClassGenerator.Console -c Release -f netcoreapp2.1
  - dotnet publish XmlSchemaClassGenerator.Console -c Release -f net45
  - dotnet pack --include-symbols --include-source -c Release XmlSchemaClassGenerator
  - dotnet pack --include-symbols --include-source -c Release XmlSchemaClassGenerator.Console
test_script:
  - dotnet test XmlSchemaClassGenerator.Tests\XmlSchemaClassGenerator.Tests.csproj
  - nuget.exe install OpenCover -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -filter:"+[XmlSchemaClassGenerator]*" -target:"C:\Program Files\dotnet\dotnet.exe" "-targetargs:test XmlSchemaClassGenerator.Tests\XmlSchemaClassGenerator.Tests.csproj" -returntargetcode -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'XmlSchemaClassGenerator\**\*.nupkg'
  - path: 'XmlSchemaClassGenerator.Console\**\*.nupkg'
