version: 2.0.{build}
skip_tags: true
image: Visual Studio 2017 Preview
build_script:
  - ps: (Get-Content XmlSchemaClassGenerator\XmlSchemaClassGenerator.csproj).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content XmlSchemaClassGenerator\XmlSchemaClassGenerator.csproj
  - ps: (Get-Content XmlSchemaClassGenerator.Console\XmlSchemaClassGenerator.Console.csproj).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content XmlSchemaClassGenerator.Console\XmlSchemaClassGenerator.Console.csproj
  - ps: (Get-Content xscgen\xscgen.csproj).Replace("1.0.0-VERSION", $env:APPVEYOR_BUILD_VERSION) | Set-Content xscgen\xscgen.csproj
  - dotnet --info
  - dotnet restore
  - dotnet build -c Release
  - dotnet publish XmlSchemaClassGenerator.Console -c Release -f net45
  - dotnet pack --include-symbols --include-source -c Release XmlSchemaClassGenerator
  - dotnet pack --include-symbols --include-source -c Release XmlSchemaClassGenerator.Console
  - dotnet pack --include-symbols --include-source -c Release xscgen
  - 7z a -mx=9 XmlSchemaClassGenerator.%APPVEYOR_BUILD_VERSION%.zip ".\XmlSchemaClassGenerator.Console\bin\Release\net45\publish\*"
test_script:
  - dotnet test XmlSchemaClassGenerator.Tests\XmlSchemaClassGenerator.Tests.csproj
  - nuget.exe install OpenCover -ExcludeVersion
  - OpenCover\tools\OpenCover.Console.exe -register:user -filter:"+[XmlSchemaClassGenerator]*" -target:"C:\Program Files\dotnet\dotnet.exe" "-targetargs:test XmlSchemaClassGenerator.Tests\XmlSchemaClassGenerator.Tests.csproj" -returntargetcode -hideskipped:All -output:coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"
artifacts:
  - path: 'XmlSchemaClassGenerator\**\*.nupkg'
  - path: 'XmlSchemaClassGenerator.Console\**\*.nupkg'
  - path: 'xscgen\**\*.nupkg'
  - path: XmlSchemaClassGenerator.%APPVEYOR_BUILD_VERSION%.zip
